---
- name: "Ensure the '/var/cache/bind/' directory exists"
  ansible.builtin.file:
    path: "/var/cache/bind/"
    state: "directory"
    owner: "root"
    group: "bind"
    mode: "0665"

- name: "Copying files to the target node"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "bind"
    mode: "0664"
  loop:
    - { src: "named", dest: "/etc/default/named" }
    - { src: "named.conf.j2", dest: "{{ bind_path }}/named.conf" }
    - { src: "zones/forward.lan.homelab.j2", dest: "/var/cache/bind/forward.lan.homelab" }
    - { src: "zones/reverse.lan.homelab.j2", dest: "/var/cache/bind/reverse.lan.homelab" }
  notify: "Restart Bind9"
